# Vacation mode for Living Room light

# Light on 30 mins before sunset
- alias: 'Vacation Mode for Lights ON'
  trigger:
    platform: time
    # Matches every hour at 5 minutes past whole
    minutes: 0
    seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.vacation_lights

# Light off 1hr 30 mins after sunset
- alias: Vacation Mode for Lights OFF'
  trigger:
    platform: time
    # Matches every hour at 5 minutes past whole
    minutes: 2
    seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: light.turn_off
    entity_id: group.vacation_lights


